data.table Reverse Dependency Checks

This is code for checking all reverse dependencies of R package
data.table. It is designed to be run in the context of a [[SLURM][SLURM]] cluster
such as [[https://in.nau.edu/arc/details/][Monsoon]] at Northern Arizona University.

** Overview of scripts

[[file:params.R]] launches the revdep checks, by first building data.table
from github master, and optionally rebuilding R itself, then
- using sbatch with a job array, each task for a different revdep to
  check via [[file:check_one.R]]
- using sbatch with --depend=afterany:JOBID to run [[file:analyze.R]] to
  make the [[https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/][output web page]] after all the checks finish.
- using sbatch with --begin=tomorrow at 00:01 to run [[file:params.R]]
  again, which will start the checks tomorrow.

** Software required

The scripts are currently highly specific to data.table and to the NAU
Monsoon cluster. System libraries required to build R packages are
installed in my [[file:emacs1-env-from-history.yml][conda environment]] and/or home directory:

#+BEGIN_SRC 
th798@wind:~/src$ ls
QuantLib-1.28	 icu		     openssl-1.1.1s  rasqal-0.9.33
SYMPHONY-5.6.17  icu4c-70_1-src.tgz  raptor2-2.0.15  redland-1.0.17
#+END_SRC

ICU 70 is installed under $HOME (for redland), and ICU 58 is installed
under $CONDA_PREFIX (for base R).

** Testing status

This software is highly experimental and has not been extensively tested. 
